#!/usr/bin/expect -f
spawn ./install-oci8.sh
expect "Please provide the path to the ORACLE_HOME directory. Use 'instantclient,/path/to/instant/client/lib' if you're compiling with Oracle Instant Client \[autodetect\]: \r"
send -- "instantclient,/opt/oracle/instantclient_12_2\r"
expect eof
